### ISSUE TITLE
allWithMatching algorithm misses help needs

### ISSUE THREAD

**Issue by jak78** [FortezaPaula/francaisaletranger#72]
Given 100 people that asked for help
And among them, 20 people can be matched with helpers
When I display the admin screen with 10 people to help (MATCHING_LIMIT)
And these 10 people are not amongst the 20
Then the screen displays no one to help
But I could help 20 people  

To fix that, we could:
- remove the limit & sort by score desc in-memory, if not too RAM-expensive
- or: compute the whole thing with one SQL query and sort by scoring desc 
- or a batch, in last resort.

**Comment by jja-octo** [comment]
If we integrate this PR: https://github.com/octo-webf/francaisaletranger-api/pull/5 we won't have this problem anymore because MATCHING_LIMIT will be removed.
